name: JackScript CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches:
      - '*'
  schedule:
    - cron:  '0 0,12 * * *'

jobs:
  ios:
    runs-on: macos-12
    steps:
      - uses: actions/checkout@v2
      - run: |
            xcodebuild clean test \
              -configuration Debug \
              -scheme "JackScript" \
              -sdk "iphonesimulator" \
              -destination "platform=iOS Simulator,name=iPhone 13" \
              ONLY_ACTIVE_ARCH=NO CODE_SIGNING_REQUIRED=NO

  tvos:
    runs-on: macos-12
    steps:
      - uses: actions/checkout@v2
      - run: |
            xcodebuild clean test \
              -configuration Debug \
              -scheme "JackScript" \
              -sdk "appletvsimulator" \
              -destination "platform=tvOS Simulator,name=Apple TV" \
              ONLY_ACTIVE_ARCH=NO CODE_SIGNING_REQUIRED=NO

  macos:
    runs-on: macos-12
    steps:
      - uses: actions/checkout@v2
      - name: Test (Debug)
        run: swift test -v --configuration release -Xswiftc -enable-testing

